[package]
name = "rust_simple_kernel"
version = "0.1.0"
authors = ["Martin Wallace <martin.v.wallace@ieee.org>"]

[lib]
crate-type = ["staticlib"]

[dependencies]
rlibc = "0.1.4"
volatile = "0.1.0"
spin = "0.4.5"

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
